// ============================================================================
// AlgoSpeak Compiler — x86-64 NASM Code Generator
// ============================================================================
// Walks the AST and emits NASM-compatible x86-64 assembly targeting Linux.
//
// Design decisions:
//  • Stack-based variable storage: each variable gets an 8-byte slot relative
//    to RBP.  Arrays store {length, elem0, elem1, …} contiguously.
//  • Stacks store {capacity, top_index, elem0, elem1, …} — max 256 elements.
//  • Queues store {capacity, head, tail, count, elem0, …} — max 256 elements.
//  • Expressions evaluate into RAX.
//  • Binary ops: eval left → push rax; eval right → pop rcx; operate.
//  • Functions follow the System V AMD64 calling convention (args in
//    rdi, rsi, rdx, rcx, r8, r9; return in rax).
//  • The runtime provides _print_int (integer → stdout), _print_newline,
//    _print_string, _bounds_error, _sort_array, and _reverse_array.
//  • Array accesses emit bounds checks that jump to _bounds_error on failure.
//  • No LLVM, no complex IR — AST → assembly for maximum compilation speed.
// ============================================================================

use std::collections::HashMap;
use crate::ast::*;

/// Maximum capacity for stacks and queues (elements).
const DS_CAPACITY: usize = 256;

pub struct CodeGen {
    /// Accumulated assembly output lines.
    output: Vec<String>,
    /// Map variable name → RBP offset (negative).
    vars: HashMap<String, VarInfo>,
    /// Next available RBP offset (grows negative).
    stack_offset: i64,
    /// Monotonically increasing label counter for unique labels.
    label_counter: usize,
    /// Track which functions have been defined (to emit them after _start).
    functions: Vec<FuncInfo>,
    /// Current loop exit label (for `stop` / break).
    loop_exit_label: Option<String>,
    /// String literals table: label → string content.
    string_literals: Vec<(String, String)>,
}

#[derive(Clone, Debug)]
struct VarInfo {
    offset: i64,
    kind: VarKind,
}

#[derive(Clone, Debug)]
enum VarKind {
    Scalar,
    Array { len: usize },
    /// Stack: [capacity, top_index, elem0, elem1, ...]
    Stack,
    /// Queue: [capacity, head, tail, count, elem0, elem1, ...]
    Queue,
}

#[derive(Clone)]
struct FuncInfo {
    name: String,
    params: Vec<String>,
    body: Vec<Stmt>,
}

impl CodeGen {
    pub fn new() -> Self {
        Self {
            output: Vec::new(),
            vars: HashMap::new(),
            stack_offset: 0,
            label_counter: 0,
            functions: Vec::new(),
            loop_exit_label: None,
            string_literals: Vec::new(),
        }
    }

    fn emit(&mut self, line: &str) {
        self.output.push(line.to_string());
    }

    fn new_label(&mut self, prefix: &str) -> String {
        self.label_counter += 1;
        format!(".L{}_{}", prefix, self.label_counter)
    }

    /// Register a string literal, returning its assembly label.
    fn add_string_literal(&mut self, s: &str) -> String {
        let label = format!("_str_{}", self.string_literals.len());
        self.string_literals.push((label.clone(), s.to_string()));
        label
    }

    /// Allocate `slots` 8-byte stack slots, return the RBP offset of the first.
    fn alloc_stack(&mut self, slots: usize) -> i64 {
        self.stack_offset -= (slots as i64) * 8;
        self.stack_offset
    }

    // ────────────────────────────────────────────────────────────────────────
    // Public entry point
    // ────────────────────────────────────────────────────────────────────────

    pub fn generate(&mut self, program: &Program) -> String {
        // Separate function definitions from top-level code.
        let mut top_level: Vec<Stmt> = Vec::new();
        for stmt in &program.statements {
            if let Stmt::FunctionDef { name, params, body } = stmt {
                self.functions.push(FuncInfo {
                    name: name.clone(),
                    params: params.clone(),
                    body: body.clone(),
                });
            } else {
                top_level.push(stmt.clone());
            }
        }

        // ── Header ──────────────────────────────────────────────────────
        self.emit("; ──────────────────────────────────────────────────────");
        self.emit("; Generated by the AlgoSpeak compiler");
        self.emit("; Target: x86-64 Linux (NASM syntax)");
        self.emit("; ──────────────────────────────────────────────────────");
        self.emit("section .text");
        self.emit("global _start");
        self.emit("");

        // ── Emit function bodies first ──────────────────────────────────
        let funcs = self.functions.clone();
        for func in &funcs {
            self.emit_function(func);
        }

        // ── _start ─────────────────────────────────────────────────────
        self.emit("_start:");
        self.emit("    push rbp");
        self.emit("    mov rbp, rsp");
        // Reserve generous stack space for top-level variables
        self.emit("    sub rsp, 65536");
        self.emit("");

        for stmt in &top_level {
            self.emit_stmt(stmt);
        }

        // ── Exit cleanly ────────────────────────────────────────────────
        self.emit("");
        self.emit("    ; exit(0)");
        self.emit("    mov rax, 60");
        self.emit("    xor rdi, rdi");
        self.emit("    syscall");
        self.emit("");

        // ── Runtime routines ────────────────────────────────────────────
        self.emit_runtime();

        // ── Data section ────────────────────────────────────────────────
        self.emit("section .bss");
        self.emit("    _printbuf resb 21        ; buffer for _print_int");
        self.emit("");
        self.emit("section .data");
        self.emit("    _newline db 10");
        self.emit("    _bounds_msg db \"Runtime error: array index out of bounds\", 10");
        self.emit("    _bounds_msg_len equ $ - _bounds_msg");
        self.emit("    _stack_underflow_msg db \"Runtime error: stack underflow\", 10");
        self.emit("    _stack_underflow_msg_len equ $ - _stack_underflow_msg");
        self.emit("    _stack_overflow_msg db \"Runtime error: stack overflow\", 10");
        self.emit("    _stack_overflow_msg_len equ $ - _stack_overflow_msg");
        self.emit("    _queue_underflow_msg db \"Runtime error: queue underflow\", 10");
        self.emit("    _queue_underflow_msg_len equ $ - _queue_underflow_msg");
        self.emit("    _queue_overflow_msg db \"Runtime error: queue overflow\", 10");
        self.emit("    _queue_overflow_msg_len equ $ - _queue_overflow_msg");

        // Emit string literals
        for (label, content) in &self.string_literals.clone() {
            // Escape for NASM
            let bytes: Vec<String> = content.bytes().map(|b| format!("{}", b)).collect();
            if bytes.is_empty() {
                self.emit(&format!("    {} db 0", label));
                self.emit(&format!("    {}_len equ 0", label));
            } else {
                self.emit(&format!("    {} db {}", label, bytes.join(",")));
                self.emit(&format!("    {}_len equ $ - {}", label, label));
            }
        }

        self.output.join("\n")
    }

    // ────────────────────────────────────────────────────────────────────────
    // Statement code generation
    // ────────────────────────────────────────────────────────────────────────

    fn emit_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::VarDecl { name, value } => self.emit_var_decl(name, value),
            Stmt::Assignment { name, index, value } => self.emit_assignment(name, index, value),
            Stmt::Show(expr) => {
                match expr {
                    Expr::StringLit(s) => {
                        let label = self.add_string_literal(s);
                        self.emit(&format!("    ; show string \"{}\"", s));
                        self.emit("    mov rax, 1");
                        self.emit("    mov rdi, 1");
                        self.emit(&format!("    lea rsi, [{}]", label));
                        self.emit(&format!("    mov rdx, {}_len", label));
                        self.emit("    syscall");
                        self.emit("    call _print_newline");
                    }
                    _ => {
                        self.emit_expr(expr);
                        self.emit("    ; show");
                        self.emit("    call _print_int");
                        self.emit("    call _print_newline");
                    }
                }
            }
            Stmt::If {
                condition,
                then_body,
                else_body,
            } => self.emit_if(condition, then_body, else_body),
            Stmt::While { condition, body } => self.emit_while(condition, body),
            Stmt::ForEach { var, iterable, body } => self.emit_for_each(var, iterable, body),
            Stmt::FunctionDef { .. } => {
                // Already handled at top level
            }
            Stmt::Return(expr) => {
                self.emit_expr(expr);
                self.emit("    ; reveal — return value in rax");
                self.emit("    mov rsp, rbp");
                self.emit("    pop rbp");
                self.emit("    ret");
            }
            Stmt::Stop => {
                if let Some(label) = &self.loop_exit_label.clone() {
                    self.emit(&format!("    jmp {}", label));
                } else {
                    // Outside a loop, stop means exit
                    self.emit("    mov rax, 60");
                    self.emit("    xor rdi, rdi");
                    self.emit("    syscall");
                }
            }
            Stmt::ExprStmt(expr) => {
                self.emit_expr(expr);
                // result in rax is discarded
            }

            // ── Data structure operations ───────────────────────────────
            Stmt::StackDecl { name } => self.emit_stack_decl(name),
            Stmt::QueueDecl { name } => self.emit_queue_decl(name),
            Stmt::PushStmt { value, target } => self.emit_push(value, target),
            Stmt::PopStmt { target } => self.emit_pop(target),
            Stmt::EnqueueStmt { value, target } => self.emit_enqueue(value, target),
            Stmt::DequeueStmt { target } => self.emit_dequeue(target),
            Stmt::SortStmt { array } => self.emit_sort(array),
            Stmt::ReverseStmt { array } => self.emit_reverse(array),
        }
    }

    fn emit_var_decl(&mut self, name: &str, value: &Expr) {
        match value {
            Expr::ArrayLiteral(elements) => {
                let len = elements.len();
                // Layout: [length, elem0, elem1, ...]
                let offset = self.alloc_stack(1 + len);
                self.vars.insert(
                    name.to_string(),
                    VarInfo {
                        offset,
                        kind: VarKind::Array { len },
                    },
                );
                // Store length
                self.emit(&format!("    ; create {} as array[{}]", name, len));
                self.emit(&format!("    mov qword [rbp{:+}], {}", offset, len));
                // Store each element
                for (i, elem) in elements.iter().enumerate() {
                    self.emit_expr(elem);
                    let elem_offset = offset + ((i as i64 + 1) * 8);
                    self.emit(&format!("    mov [rbp{:+}], rax", elem_offset));
                }
            }
            _ => {
                let offset = self.alloc_stack(1);
                self.vars.insert(
                    name.to_string(),
                    VarInfo {
                        offset,
                        kind: VarKind::Scalar,
                    },
                );
                self.emit_expr(value);
                self.emit(&format!("    ; create {} as scalar", name));
                self.emit(&format!("    mov [rbp{:+}], rax", offset));
            }
        }
    }

    fn emit_assignment(&mut self, name: &str, index: &Option<Box<Expr>>, value: &Expr) {
        if let Some(idx_expr) = index {
            // Array element assignment: set arr[i] to value
            let info = self.vars.get(name).cloned().expect("undeclared variable");
            let base_offset = info.offset;
            let arr_len = if let VarKind::Array { len } = info.kind {
                len
            } else {
                0
            };

            // Evaluate index → push
            self.emit_expr(idx_expr);
            self.emit("    push rax");

            // Evaluate value → push
            self.emit_expr(value);
            self.emit("    push rax");

            // Pop value into rdx, index into rcx
            self.emit("    pop rdx");    // value
            self.emit("    pop rcx");    // index

            // Bounds check
            let ok_label = self.new_label("bounds_ok");
            self.emit(&format!("    ; bounds check for {}[]", name));
            self.emit("    cmp rcx, 0");
            self.emit("    jl _bounds_error");
            self.emit(&format!("    cmp rcx, {}", arr_len));
            self.emit("    jge _bounds_error");
            self.emit(&format!("{}:", ok_label));

            // Store: address = rbp + base_offset + (index+1)*8
            self.emit("    inc rcx");
            self.emit("    imul rcx, 8");
            self.emit(&format!("    lea rax, [rbp{:+}]", base_offset));
            self.emit("    add rax, rcx");
            self.emit("    mov [rax], rdx");
        } else {
            // Simple scalar assignment
            let info = self.vars.get(name).cloned().expect("undeclared variable");
            self.emit_expr(value);
            self.emit(&format!("    ; set {} to value", name));
            self.emit(&format!("    mov [rbp{:+}], rax", info.offset));
        }
    }

    fn emit_if(&mut self, condition: &Expr, then_body: &[Stmt], else_body: &[Stmt]) {
        let else_label = self.new_label("else");
        let end_label = self.new_label("endif");

        self.emit_expr(condition);
        self.emit("    cmp rax, 0");
        self.emit(&format!("    je {}", else_label));

        for s in then_body {
            self.emit_stmt(s);
        }
        self.emit(&format!("    jmp {}", end_label));

        self.emit(&format!("{}:", else_label));
        for s in else_body {
            self.emit_stmt(s);
        }

        self.emit(&format!("{}:", end_label));
    }

    fn emit_while(&mut self, condition: &Expr, body: &[Stmt]) {
        let loop_label = self.new_label("while");
        let end_label = self.new_label("endwhile");

        let prev_exit = self.loop_exit_label.clone();
        self.loop_exit_label = Some(end_label.clone());

        self.emit(&format!("{}:", loop_label));
        self.emit_expr(condition);
        self.emit("    cmp rax, 0");
        self.emit(&format!("    je {}", end_label));

        for s in body {
            self.emit_stmt(s);
        }
        self.emit(&format!("    jmp {}", loop_label));
        self.emit(&format!("{}:", end_label));

        self.loop_exit_label = prev_exit;
    }

    fn emit_for_each(&mut self, var: &str, iterable: &str, body: &[Stmt]) {
        let iter_info = self.vars.get(iterable).cloned().expect("undeclared iterable");
        let arr_len = if let VarKind::Array { len } = iter_info.kind {
            len
        } else {
            0
        };
        let base_offset = iter_info.offset;

        // Allocate the loop variable
        let var_offset = self.alloc_stack(1);
        self.vars.insert(
            var.to_string(),
            VarInfo {
                offset: var_offset,
                kind: VarKind::Scalar,
            },
        );

        // Allocate a hidden index variable
        let idx_offset = self.alloc_stack(1);

        let loop_label = self.new_label("foreach");
        let end_label = self.new_label("endforeach");

        let prev_exit = self.loop_exit_label.clone();
        self.loop_exit_label = Some(end_label.clone());

        // Initialize index to 0
        self.emit(&format!("    ; for each {} in {}", var, iterable));
        self.emit(&format!("    mov qword [rbp{:+}], 0", idx_offset));

        self.emit(&format!("{}:", loop_label));
        // Load index, compare with length
        self.emit(&format!("    mov rcx, [rbp{:+}]", idx_offset));
        self.emit(&format!("    cmp rcx, {}", arr_len));
        self.emit(&format!("    jge {}", end_label));

        // Load current element: base + (index+1)*8
        self.emit(&format!("    mov rcx, [rbp{:+}]", idx_offset));
        self.emit("    inc rcx");
        self.emit("    imul rcx, 8");
        self.emit(&format!("    lea rax, [rbp{:+}]", base_offset));
        self.emit("    add rax, rcx");
        self.emit("    mov rax, [rax]");
        self.emit(&format!("    mov [rbp{:+}], rax", var_offset));

        for s in body {
            self.emit_stmt(s);
        }

        // Increment index
        self.emit(&format!("    inc qword [rbp{:+}]", idx_offset));
        self.emit(&format!("    jmp {}", loop_label));
        self.emit(&format!("{}:", end_label));

        self.loop_exit_label = prev_exit;
    }

    fn emit_function(&mut self, func: &FuncInfo) {
        let saved_vars = self.vars.clone();
        let saved_offset = self.stack_offset;
        self.vars.clear();
        self.stack_offset = 0;

        self.emit(&format!("{}:", func.name));
        self.emit("    push rbp");
        self.emit("    mov rbp, rsp");
        self.emit("    sub rsp, 4096");

        // Map parameters from registers to stack slots
        let regs = ["rdi", "rsi", "rdx", "rcx", "r8", "r9"];
        for (i, param) in func.params.iter().enumerate() {
            let offset = self.alloc_stack(1);
            self.vars.insert(
                param.clone(),
                VarInfo {
                    offset,
                    kind: VarKind::Scalar,
                },
            );
            if i < regs.len() {
                self.emit(&format!("    mov [rbp{:+}], {}", offset, regs[i]));
            }
        }

        for stmt in &func.body {
            self.emit_stmt(stmt);
        }

        // Default return 0 if no explicit reveal
        self.emit("    xor rax, rax");
        self.emit("    mov rsp, rbp");
        self.emit("    pop rbp");
        self.emit("    ret");
        self.emit("");

        // Restore outer scope
        self.vars = saved_vars;
        self.stack_offset = saved_offset;
    }

    // ────────────────────────────────────────────────────────────────────────
    // Data structure operations
    // ────────────────────────────────────────────────────────────────────────

    /// Stack layout: [capacity(256), top_index(0), elem0, elem1, ...]
    fn emit_stack_decl(&mut self, name: &str) {
        // Allocate: 2 metadata slots + DS_CAPACITY element slots
        let offset = self.alloc_stack(2 + DS_CAPACITY);
        self.vars.insert(
            name.to_string(),
            VarInfo {
                offset,
                kind: VarKind::Stack,
            },
        );
        self.emit(&format!("    ; create stack {}", name));
        // Store capacity
        self.emit(&format!("    mov qword [rbp{:+}], {}", offset, DS_CAPACITY));
        // Store top = 0 (empty)
        self.emit(&format!("    mov qword [rbp{:+}], 0", offset + 8));
    }

    /// Push value onto stack: increment top, store element
    fn emit_push(&mut self, value: &Expr, target: &str) {
        let info = self.vars.get(target).cloned().expect("undeclared stack");
        let base = info.offset;

        self.emit_expr(value);
        self.emit("    push rax");  // save value

        // Check overflow: top < capacity
        let ok_label = self.new_label("push_ok");
        self.emit(&format!("    ; push into {}", target));
        self.emit(&format!("    mov rcx, [rbp{:+}]", base + 8));  // top
        self.emit(&format!("    cmp rcx, {}", DS_CAPACITY));
        self.emit(&format!("    jl {}", ok_label));
        self.emit("    jmp _stack_overflow_error");
        self.emit(&format!("{}:", ok_label));

        // Store element at base + (2 + top) * 8
        self.emit("    pop rax");  // restore value
        self.emit(&format!("    mov rcx, [rbp{:+}]", base + 8));  // top
        self.emit("    add rcx, 2");
        self.emit("    imul rcx, 8");
        self.emit(&format!("    lea rdx, [rbp{:+}]", base));
        self.emit("    add rdx, rcx");
        self.emit("    mov [rdx], rax");

        // Increment top
        self.emit(&format!("    inc qword [rbp{:+}]", base + 8));
    }

    /// Pop from stack: decrement top, load element into rax
    fn emit_pop(&mut self, target: &str) {
        let info = self.vars.get(target).cloned().expect("undeclared stack");
        let base = info.offset;

        // Check underflow: top > 0
        let ok_label = self.new_label("pop_ok");
        self.emit(&format!("    ; pop from {}", target));
        self.emit(&format!("    mov rcx, [rbp{:+}]", base + 8));  // top
        self.emit("    cmp rcx, 0");
        self.emit(&format!("    jg {}", ok_label));
        self.emit("    jmp _stack_underflow_error");
        self.emit(&format!("{}:", ok_label));

        // Decrement top
        self.emit(&format!("    dec qword [rbp{:+}]", base + 8));

        // Load element from base + (2 + new_top) * 8
        self.emit(&format!("    mov rcx, [rbp{:+}]", base + 8));  // new top
        self.emit("    add rcx, 2");
        self.emit("    imul rcx, 8");
        self.emit(&format!("    lea rax, [rbp{:+}]", base));
        self.emit("    add rax, rcx");
        self.emit("    mov rax, [rax]");
    }

    /// Queue layout: [capacity(256), head(0), tail(0), count(0), elem0, ...]
    fn emit_queue_decl(&mut self, name: &str) {
        // Allocate: 4 metadata slots + DS_CAPACITY element slots
        let offset = self.alloc_stack(4 + DS_CAPACITY);
        self.vars.insert(
            name.to_string(),
            VarInfo {
                offset,
                kind: VarKind::Queue,
            },
        );
        self.emit(&format!("    ; create queue {}", name));
        self.emit(&format!("    mov qword [rbp{:+}], {}", offset, DS_CAPACITY));
        self.emit(&format!("    mov qword [rbp{:+}], 0", offset + 8));   // head
        self.emit(&format!("    mov qword [rbp{:+}], 0", offset + 16));  // tail
        self.emit(&format!("    mov qword [rbp{:+}], 0", offset + 24));  // count
    }

    /// Enqueue: store at tail, increment tail (circular), increment count
    fn emit_enqueue(&mut self, value: &Expr, target: &str) {
        let info = self.vars.get(target).cloned().expect("undeclared queue");
        let base = info.offset;

        self.emit_expr(value);
        self.emit("    push rax");

        // Check overflow: count < capacity
        let ok_label = self.new_label("enq_ok");
        self.emit(&format!("    ; enqueue into {}", target));
        self.emit(&format!("    mov rcx, [rbp{:+}]", base + 24));  // count
        self.emit(&format!("    cmp rcx, {}", DS_CAPACITY));
        self.emit(&format!("    jl {}", ok_label));
        self.emit("    jmp _queue_overflow_error");
        self.emit(&format!("{}:", ok_label));

        // Store at tail: base + (4 + tail) * 8
        self.emit("    pop rax");
        self.emit(&format!("    mov rcx, [rbp{:+}]", base + 16));  // tail
        self.emit("    add rcx, 4");
        self.emit("    imul rcx, 8");
        self.emit(&format!("    lea rdx, [rbp{:+}]", base));
        self.emit("    add rdx, rcx");
        self.emit("    mov [rdx], rax");

        // tail = (tail + 1) % capacity
        self.emit(&format!("    mov rax, [rbp{:+}]", base + 16));
        self.emit("    inc rax");
        self.emit("    xor rdx, rdx");
        self.emit(&format!("    mov rcx, {}", DS_CAPACITY));
        self.emit("    div rcx");
        self.emit(&format!("    mov [rbp{:+}], rdx", base + 16));  // tail = remainder

        // Increment count
        self.emit(&format!("    inc qword [rbp{:+}]", base + 24));
    }

    /// Dequeue: load from head, increment head (circular), decrement count
    fn emit_dequeue(&mut self, target: &str) {
        let info = self.vars.get(target).cloned().expect("undeclared queue");
        let base = info.offset;

        // Check underflow: count > 0
        let ok_label = self.new_label("deq_ok");
        self.emit(&format!("    ; dequeue from {}", target));
        self.emit(&format!("    mov rcx, [rbp{:+}]", base + 24));  // count
        self.emit("    cmp rcx, 0");
        self.emit(&format!("    jg {}", ok_label));
        self.emit("    jmp _queue_underflow_error");
        self.emit(&format!("{}:", ok_label));

        // Load from head: base + (4 + head) * 8
        self.emit(&format!("    mov rcx, [rbp{:+}]", base + 8));  // head
        self.emit("    add rcx, 4");
        self.emit("    imul rcx, 8");
        self.emit(&format!("    lea rax, [rbp{:+}]", base));
        self.emit("    add rax, rcx");
        self.emit("    mov rax, [rax]");

        // head = (head + 1) % capacity
        self.emit("    push rax");  // save dequeued value
        self.emit(&format!("    mov rax, [rbp{:+}]", base + 8));
        self.emit("    inc rax");
        self.emit("    xor rdx, rdx");
        self.emit(&format!("    mov rcx, {}", DS_CAPACITY));
        self.emit("    div rcx");
        self.emit(&format!("    mov [rbp{:+}], rdx", base + 8));  // head = remainder

        // Decrement count
        self.emit(&format!("    dec qword [rbp{:+}]", base + 24));

        self.emit("    pop rax");  // restore dequeued value
    }

    /// Sort an array in-place using bubble sort in assembly.
    fn emit_sort(&mut self, array: &str) {
        let info = self.vars.get(array).cloned().expect("undeclared array");
        let base = info.offset;
        let len = if let VarKind::Array { len } = info.kind { len } else { 0 };

        // Pass: base address of elements (base + 8) and length
        self.emit(&format!("    ; sort {}", array));
        self.emit(&format!("    lea rdi, [rbp{:+}]", base + 8));  // pointer to elem0
        self.emit(&format!("    mov rsi, {}", len));               // length
        self.emit("    call _sort_array");
    }

    /// Reverse an array in-place.
    fn emit_reverse(&mut self, array: &str) {
        let info = self.vars.get(array).cloned().expect("undeclared array");
        let base = info.offset;
        let len = if let VarKind::Array { len } = info.kind { len } else { 0 };

        self.emit(&format!("    ; reverse {}", array));
        self.emit(&format!("    lea rdi, [rbp{:+}]", base + 8));  // pointer to elem0
        self.emit(&format!("    mov rsi, {}", len));               // length
        self.emit("    call _reverse_array");
    }

    // ────────────────────────────────────────────────────────────────────────
    // Expression code generation — result always in RAX
    // ────────────────────────────────────────────────────────────────────────

    fn emit_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::NumberLit(n) => {
                self.emit(&format!("    mov rax, {}", n));
            }

            Expr::StringLit(s) => {
                // String literal as expression — return address (rarely used directly)
                let label = self.add_string_literal(s);
                self.emit(&format!("    lea rax, [{}]", label));
            }

            Expr::Var(name) => {
                let info = self.vars.get(name).cloned().expect("undeclared variable");
                self.emit(&format!("    mov rax, [rbp{:+}]", info.offset));
            }

            Expr::UnaryMinus(inner) => {
                self.emit_expr(inner);
                self.emit("    neg rax");
            }

            Expr::BinaryOp { left, op, right } => {
                self.emit_expr(left);
                self.emit("    push rax");
                self.emit_expr(right);
                self.emit("    mov rcx, rax");  // right operand
                self.emit("    pop rax");        // left operand

                match op {
                    BinOp::Add => {
                        self.emit("    add rax, rcx");
                    }
                    BinOp::Sub => {
                        self.emit("    sub rax, rcx");
                    }
                    BinOp::Mul => {
                        self.emit("    imul rax, rcx");
                    }
                    BinOp::Div => {
                        self.emit("    cqo");
                        self.emit("    idiv rcx");
                    }
                    BinOp::Mod => {
                        self.emit("    cqo");
                        self.emit("    idiv rcx");
                        self.emit("    mov rax, rdx");  // remainder
                    }
                    BinOp::Eq => {
                        self.emit("    cmp rax, rcx");
                        self.emit("    sete al");
                        self.emit("    movzx rax, al");
                    }
                    BinOp::Neq => {
                        self.emit("    cmp rax, rcx");
                        self.emit("    setne al");
                        self.emit("    movzx rax, al");
                    }
                    BinOp::Lt => {
                        self.emit("    cmp rax, rcx");
                        self.emit("    setl al");
                        self.emit("    movzx rax, al");
                    }
                    BinOp::Gt => {
                        self.emit("    cmp rax, rcx");
                        self.emit("    setg al");
                        self.emit("    movzx rax, al");
                    }
                    BinOp::Le => {
                        self.emit("    cmp rax, rcx");
                        self.emit("    setle al");
                        self.emit("    movzx rax, al");
                    }
                    BinOp::Ge => {
                        self.emit("    cmp rax, rcx");
                        self.emit("    setge al");
                        self.emit("    movzx rax, al");
                    }
                    BinOp::And => {
                        // Logical AND: (a != 0) & (b != 0)
                        self.emit("    test rax, rax");
                        self.emit("    setne al");
                        self.emit("    test rcx, rcx");
                        self.emit("    setne cl");
                        self.emit("    and al, cl");
                        self.emit("    movzx rax, al");
                    }
                    BinOp::Or => {
                        // Logical OR: (a != 0) | (b != 0)
                        self.emit("    or rax, rcx");
                        self.emit("    test rax, rax");
                        self.emit("    setne al");
                        self.emit("    movzx rax, al");
                    }
                }
            }

            Expr::ArrayLiteral(_) => {
                // Array literals as expressions should only appear in VarDecl
                // which is handled specially. If we get here, just return 0.
                self.emit("    xor rax, rax");
            }

            Expr::ArrayAccess { array, index } => {
                let info = self.vars.get(array).cloned().expect("undeclared variable");
                let base_offset = info.offset;
                let arr_len = if let VarKind::Array { len } = info.kind {
                    len
                } else {
                    0
                };

                self.emit_expr(index);
                // rax = index value
                // Bounds check
                self.emit(&format!("    ; bounds check for {}[]", array));
                self.emit("    cmp rax, 0");
                self.emit("    jl _bounds_error");
                self.emit(&format!("    cmp rax, {}", arr_len));
                self.emit("    jge _bounds_error");

                // Load element: base + (index+1)*8
                self.emit("    inc rax");
                self.emit("    imul rax, 8");
                self.emit(&format!("    lea rcx, [rbp{:+}]", base_offset));
                self.emit("    add rax, rcx");
                self.emit("    mov rax, [rax]");
            }

            Expr::LengthOf(name) => {
                let info = self.vars.get(name).cloned().expect("undeclared variable");
                // Length is stored at the base offset
                self.emit(&format!("    mov rax, [rbp{:+}]", info.offset));
            }

            Expr::FunctionCall { name, args } => {
                // Push args right-to-left, then move to registers
                let regs = ["rdi", "rsi", "rdx", "rcx", "r8", "r9"];

                // Evaluate each argument and push
                for arg in args.iter() {
                    self.emit_expr(arg);
                    self.emit("    push rax");
                }

                // Pop into registers in order
                for i in (0..args.len().min(regs.len())).rev() {
                    self.emit(&format!("    pop {}", regs[i]));
                }

                // Align stack to 16 bytes before call
                self.emit(&format!("    call {}", name));
            }

            Expr::PopExpr { target } => {
                self.emit_pop(target);
            }

            Expr::DequeueExpr { target } => {
                self.emit_dequeue(target);
            }
        }
    }

    // ────────────────────────────────────────────────────────────────────────
    // Runtime routines
    // ────────────────────────────────────────────────────────────────────────

    fn emit_runtime(&mut self) {
        self.emit_print_int_clean();
        self.emit_print_newline();
        self.emit_bounds_error();
        self.emit_stack_errors();
        self.emit_queue_errors();
        self.emit_sort_routine();
        self.emit_reverse_routine();
    }

    fn emit_print_int_clean(&mut self) {
        self.emit("; ── runtime: _print_int ──────────────────────────────");
        self.emit("; Prints the signed 64-bit integer in RAX to stdout.");
        self.emit("_print_int:");
        self.emit("    push rbx");
        self.emit("    push rcx");
        self.emit("    push rdx");
        self.emit("    push rsi");
        self.emit("    push rdi");
        self.emit("    push r12");
        self.emit("");
        self.emit("    mov r12, rax            ; save original value");
        self.emit("    sub rsp, 24             ; local buffer on stack");
        self.emit("    lea rsi, [rsp+23]       ; rsi = pointer to end of buffer");
        self.emit("    mov byte [rsi], 0       ; null terminate (unused but safe)");
        self.emit("    mov rcx, 0              ; digit count");
        self.emit("");
        self.emit("    ; Handle negative");
        self.emit("    test rax, rax");
        self.emit("    jns .print_positive");
        self.emit("    neg rax");
        self.emit(".print_positive:");
        self.emit("    ; Convert to digits (reverse order)");
        self.emit(".print_digit_loop:");
        self.emit("    xor rdx, rdx");
        self.emit("    mov rbx, 10");
        self.emit("    div rbx");
        self.emit("    add dl, '0'");
        self.emit("    dec rsi");
        self.emit("    mov [rsi], dl");
        self.emit("    inc rcx");
        self.emit("    test rax, rax");
        self.emit("    jnz .print_digit_loop");
        self.emit("");
        self.emit("    ; Prepend '-' if original was negative");
        self.emit("    test r12, r12");
        self.emit("    jns .print_write");
        self.emit("    dec rsi");
        self.emit("    mov byte [rsi], '-'");
        self.emit("    inc rcx");
        self.emit(".print_write:");
        self.emit("    ; write(1, rsi, rcx)");
        self.emit("    mov rax, 1              ; sys_write");
        self.emit("    mov rdi, 1              ; stdout");
        self.emit("    mov rdx, rcx            ; length");
        self.emit("    syscall");
        self.emit("");
        self.emit("    add rsp, 24");
        self.emit("    pop r12");
        self.emit("    pop rdi");
        self.emit("    pop rsi");
        self.emit("    pop rdx");
        self.emit("    pop rcx");
        self.emit("    pop rbx");
        self.emit("    ret");
        self.emit("");
    }

    fn emit_print_newline(&mut self) {
        self.emit("; ── runtime: _print_newline ──────────────────────────");
        self.emit("_print_newline:");
        self.emit("    push rcx");
        self.emit("    push rdx");
        self.emit("    push rsi");
        self.emit("    push rdi");
        self.emit("    mov rax, 1              ; sys_write");
        self.emit("    mov rdi, 1              ; stdout");
        self.emit("    lea rsi, [_newline]");
        self.emit("    mov rdx, 1              ; length");
        self.emit("    syscall");
        self.emit("    pop rdi");
        self.emit("    pop rsi");
        self.emit("    pop rdx");
        self.emit("    pop rcx");
        self.emit("    ret");
        self.emit("");
    }

    fn emit_bounds_error(&mut self) {
        self.emit("; ── runtime: _bounds_error ───────────────────────────");
        self.emit("_bounds_error:");
        self.emit("    mov rax, 1              ; sys_write");
        self.emit("    mov rdi, 2              ; stderr");
        self.emit("    lea rsi, [_bounds_msg]");
        self.emit("    mov rdx, _bounds_msg_len");
        self.emit("    syscall");
        self.emit("    mov rax, 60             ; sys_exit");
        self.emit("    mov rdi, 1              ; exit code 1");
        self.emit("    syscall");
        self.emit("");
    }

    fn emit_stack_errors(&mut self) {
        self.emit("; ── runtime: _stack_overflow_error ────────────────────");
        self.emit("_stack_overflow_error:");
        self.emit("    mov rax, 1");
        self.emit("    mov rdi, 2");
        self.emit("    lea rsi, [_stack_overflow_msg]");
        self.emit("    mov rdx, _stack_overflow_msg_len");
        self.emit("    syscall");
        self.emit("    mov rax, 60");
        self.emit("    mov rdi, 1");
        self.emit("    syscall");
        self.emit("");
        self.emit("; ── runtime: _stack_underflow_error ────────────────────");
        self.emit("_stack_underflow_error:");
        self.emit("    mov rax, 1");
        self.emit("    mov rdi, 2");
        self.emit("    lea rsi, [_stack_underflow_msg]");
        self.emit("    mov rdx, _stack_underflow_msg_len");
        self.emit("    syscall");
        self.emit("    mov rax, 60");
        self.emit("    mov rdi, 1");
        self.emit("    syscall");
        self.emit("");
    }

    fn emit_queue_errors(&mut self) {
        self.emit("; ── runtime: _queue_overflow_error ────────────────────");
        self.emit("_queue_overflow_error:");
        self.emit("    mov rax, 1");
        self.emit("    mov rdi, 2");
        self.emit("    lea rsi, [_queue_overflow_msg]");
        self.emit("    mov rdx, _queue_overflow_msg_len");
        self.emit("    syscall");
        self.emit("    mov rax, 60");
        self.emit("    mov rdi, 1");
        self.emit("    syscall");
        self.emit("");
        self.emit("; ── runtime: _queue_underflow_error ────────────────────");
        self.emit("_queue_underflow_error:");
        self.emit("    mov rax, 1");
        self.emit("    mov rdi, 2");
        self.emit("    lea rsi, [_queue_underflow_msg]");
        self.emit("    mov rdx, _queue_underflow_msg_len");
        self.emit("    syscall");
        self.emit("    mov rax, 60");
        self.emit("    mov rdi, 1");
        self.emit("    syscall");
        self.emit("");
    }

    fn emit_sort_routine(&mut self) {
        // Bubble sort: rdi = pointer to array elements, rsi = length
        self.emit("; ── runtime: _sort_array (bubble sort) ───────────────");
        self.emit("; rdi = pointer to first element, rsi = number of elements");
        self.emit("_sort_array:");
        self.emit("    push rbx");
        self.emit("    push rcx");
        self.emit("    push rdx");
        self.emit("    push r8");
        self.emit("    push r9");
        self.emit("    push r10");
        self.emit("");
        self.emit("    mov r8, rsi             ; r8 = n");
        self.emit("    cmp r8, 1");
        self.emit("    jle .sort_done");
        self.emit("");
        self.emit("    mov r9, 0               ; i = 0");
        self.emit(".sort_outer:");
        self.emit("    cmp r9, r8");
        self.emit("    jge .sort_done");
        self.emit("    mov r10, 0              ; j = 0");
        self.emit("    mov rcx, r8");
        self.emit("    sub rcx, 1");
        self.emit("    sub rcx, r9             ; rcx = n - 1 - i");
        self.emit(".sort_inner:");
        self.emit("    cmp r10, rcx");
        self.emit("    jge .sort_next_i");
        self.emit("    ; Compare arr[j] and arr[j+1]");
        self.emit("    mov rax, r10");
        self.emit("    imul rax, 8");
        self.emit("    add rax, rdi");
        self.emit("    mov rbx, [rax]          ; arr[j]");
        self.emit("    mov rdx, [rax+8]        ; arr[j+1]");
        self.emit("    cmp rbx, rdx");
        self.emit("    jle .sort_no_swap");
        self.emit("    ; Swap");
        self.emit("    mov [rax], rdx");
        self.emit("    mov [rax+8], rbx");
        self.emit(".sort_no_swap:");
        self.emit("    inc r10");
        self.emit("    jmp .sort_inner");
        self.emit(".sort_next_i:");
        self.emit("    inc r9");
        self.emit("    jmp .sort_outer");
        self.emit(".sort_done:");
        self.emit("    pop r10");
        self.emit("    pop r9");
        self.emit("    pop r8");
        self.emit("    pop rdx");
        self.emit("    pop rcx");
        self.emit("    pop rbx");
        self.emit("    ret");
        self.emit("");
    }

    fn emit_reverse_routine(&mut self) {
        // In-place reversal: rdi = pointer, rsi = length
        self.emit("; ── runtime: _reverse_array ──────────────────────────");
        self.emit("; rdi = pointer to first element, rsi = number of elements");
        self.emit("_reverse_array:");
        self.emit("    push rbx");
        self.emit("    push rcx");
        self.emit("    push rdx");
        self.emit("");
        self.emit("    mov rcx, 0              ; left = 0");
        self.emit("    mov rdx, rsi");
        self.emit("    dec rdx                  ; right = n - 1");
        self.emit(".rev_loop:");
        self.emit("    cmp rcx, rdx");
        self.emit("    jge .rev_done");
        self.emit("    ; Swap arr[left] and arr[right]");
        self.emit("    mov rax, rcx");
        self.emit("    imul rax, 8");
        self.emit("    add rax, rdi");
        self.emit("    mov rbx, rdx");
        self.emit("    imul rbx, 8");
        self.emit("    add rbx, rdi");
        self.emit("    push qword [rax]");
        self.emit("    push qword [rbx]");
        self.emit("    pop qword [rax]");
        self.emit("    pop qword [rbx]");
        self.emit("    inc rcx");
        self.emit("    dec rdx");
        self.emit("    jmp .rev_loop");
        self.emit(".rev_done:");
        self.emit("    pop rdx");
        self.emit("    pop rcx");
        self.emit("    pop rbx");
        self.emit("    ret");
        self.emit("");
    }
}
